version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start" ]
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /Users/amitkumar/srilekha/unv/idviceme/db :/data/db
    ports:
      - "27017:27017"
